# KubeArmor is open-source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor, visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-go-unsafe-pointer-code-injection
  namespace: default #change to your namespace
spec:
  tags: ["unsafepackage", "code-injection", "golang"]
  message: "Alert! usage of unsafe pointer is blocked."
  selector:
    matchLabels:
      container: ubuntu #change to your labels
  process:
    severity: 3
    matchPaths:
      - path: /usr/bin/readlink
      - path: /usr/local/go/src/unsafe/unsafe.go
    action: Block
  file:
    severity: 5
    matchPaths:
      - path: /usr/local/lib/python2.7/dist-packages/pwnlib/shellcraft/templates/amd64/linux/syscalls/mprotect.asm
      - path: /usr/local/go/src/unsafe/unsafe.go
    matchDirectories:
      - dir: /usr/local/lib/python2.7/dist-packages/pwnlib/
      - dir: /usr/lib/go-1.10/pkg/
      - dir: /usr/lib/python3/dist-packages/
      - dir: /usr/local/go/
    action: Block

