---
# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-allow-golang-generic-policy-3
  namespace: default # Change your namespace
spec:
  tags: ["golang", "generic policy"]
  selector:
    matchLabels:
      app: golang # Change your matchLabels
  file:
    severity: 5
    matchPaths:
    - path: /dev/null
      fromSource:
      - path: /usr/local/go/bin/go
    - path: /dev/tty
      fromSource:
      - path: /bin/bash
    - path: /etc/ld.so.cache
      fromSource:
      - path: /bin/ls
      - path: /sbin/ldconfig
      - path: /usr/bin/env
      - path: /usr/bin/whoami
      - path: /usr/local/go/bin/go
    - path: /etc/nsswitch.conf
      fromSource:
      - path: /usr/bin/whoami
    - path: /etc/passwd
      fromSource:
      - path: /usr/bin/whoami
    - path: /lib/terminfo/x/xterm
      fromSource:
      - path: /bin/bash
    - path: /lib/x86_64-linux-gnu/libc.so.6
      fromSource:
      - path: /bin/dash
      - path: /usr/local/go/bin/go
    - path: /root/.bashrc
      fromSource:
      - path: /bin/bash
    - path: /tmp/main.go
      fromSource:
      - path: /usr/local/go/bin/go
    matchDirectories:
    - dir: /etc/
      fromSource:
      - path: /bin/bash
    - dir: /lib/x86_64-linux-gnu/
      fromSource:
      - path: /bin/bash
      - path: /bin/ls
    - dir: /proc/
      fromSource:
      - path: /bin/bash
      - path: /bin/ls
      - path: /tmp/main
      - path: /usr/local/go/bin/go
      - path: /usr/local/go/pkg/tool/linux_amd64/asm
      - path: /usr/local/go/pkg/tool/linux_amd64/link
    - dir: /root/.cache/go-build/
      fromSource:
      - path: /usr/local/go/bin/go
    - dir: /sys/
      fromSource:
      - path: /usr/local/go/bin/go
      - path: /usr/local/go/pkg/tool/linux_amd64/asm
      - path: /usr/local/go/pkg/tool/linux_amd64/compile
      - path: /usr/local/go/pkg/tool/linux_amd64/link
    - dir: /usr/local/go/pkg/linux_amd64/
      fromSource:
      - path: /usr/local/go/bin/go
    - dir: /usr/local/go/src/
      fromSource:
      - path: /usr/local/go/bin/go
    action: Allow
