---
# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-allow-golang-generic-policy-2
  namespace: default # Change your namespace
spec:
  tags: ["golang", "generic policy"]
  selector:
    matchLabels:
      app: golang # Change your matchLabels
  process:
    severity: 5
    matchPaths:
    - path: /usr/local/go/pkg/tool/linux_amd64/asm
      fromSource:
      - path: /usr/local/go/bin/go
    - path: /usr/local/go/pkg/tool/linux_amd64/compile
      fromSource:
      - path: /usr/local/go/bin/go
    - path: /usr/local/go/pkg/tool/linux_amd64/link
      fromSource:
      - path: /usr/local/go/bin/go
    action: Allow
