# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-golang-unmarshal
  namespace: default # Change your name space
spec:
  tags: ["golang", "protobuf", "index-validation","CVE-2021-3121"]
  message: "Alert! unmarshal.go has been accessed"
  selector:
    matchLabels:
      app: golang # Change your matchLabels
  file:
    severity: 5
    matchPatterns:
      - pattern: /**/unmarshal.go
    matchPaths:
      - path: /go/src/github.com/gogo/protobuf/plugin/unmarshal/unmarshal.go
    action: Audit
