# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-misconfig-application-yaml
  namespace: default # Change your namespace
spec:
  tags: ["NUCLEI", "MISCONFIG", "YAML"]
  message: "Alert! app.yaml file access has been denied"
  selector:
    matchLabels:
      app: lfipod # Change you matchLabels
  file:
    severity: 5
    matchPatterns:
    - pattern: /**/app.yaml # Sensitive yaml files 
    - pattern: /**/app.yml 
    - pattern: /**/application.yaml
    - pattern: /**/application.yml 
    action: Block