# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-service-password-dorking-block
  namespace: default # Change to your namespace
spec:
  tags: ["sensitive", "service.pwd", "dorking", "exposure", "listing"]
  message: "blocking service.pwd file."
  selector:
    matchLabels:
      app: frontend  #Change to labels of frontend web application pod 
  file:
    severity: 6
    matchPatterns:
    - pattern: /**/service.pwd
    action: Block
