# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-mysql-v-235149-mysql-access
  namespace: default    #change default to your namespace
spec:
  tags: ["MySQL", "STIG", "V-235149"]
  message: "MySQL was accessed by a process"
  selector:
    matchLabels:
      app: mysql        #change app: mysql to your label
  process:
    matchPatterns:      
    - pattern: /**/mysql* 
    severity: 6
    action: Audit
