# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/
# https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-12-03/finding/V-230530

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-rhel-v-230530-2
  namespace: default
spec:
  tags: ["STIG", "RHEL", "V230530"]
  message: "Info! dconf has been accessed and stig rule v-230530 implemented"
  selector:
    matchLabels:
      app: redhat
  process:
    severity: 5
    matchPaths:
    - path: /usr/bin/dconf
    action: Audit
