# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

# https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-12-03/finding/V-230246

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-stig-v-230246-rhel-allow-only-root-access-to-log-files
  namespace: default # Change your namespace
spec:
  tags: ["rhel", "log", "stig", "v-230246"]
  message: "Alert! Access to log directory is detected."
  selector:
    matchLabels:
      app: redhat # Change your labels
  file:
    severity: 3
    matchDirectories:
    - dir: /var/log/
      recursive: true
      ownerOnly: true # allow access for root only
    action: Block
