# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/
# https://www.stigviewer.com/stig/vrealize_-_cassandra/2017-06-06/finding/V-72637

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-cassandra-stig-v-72637
  namespace: default # Change your namespace
spec:
  tags: ["STIG", "LOG", "CASSANDRA", "V-72637"]
  message: "Alert! Log files are accessed."
  selector:
    matchLabels:
      app: cass-server # Change your matchLabels
  file:
    matchDirectories:
    - dir: /var/log/cassandra/
      recursive: true
      ownerOnly: true
    - dir: /storage/log/vcops/log/cassandra/
      recursive: true
      ownerOnly: true
    action: Audit
