# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

# https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-12-03/finding/V-230284

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-stig-v-230284-deny-access-to-shosts-files
  namespace: default # change to your namespace if you need
spec:
  tags: ["STIG","RHEL","V-230284",".shosts"]
  message: "Alert! Access denied for .shosts files"
  selector:
    matchLabels:
       app: redhat # change your labels if you need
  file:
    severity: 4
    matchPaths:
    - path: /*.shosts
    matchPatterns:
    - pattern: /**/*.shosts
    action: Block
