# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-stig-restrict-non-mysql-binaries
  namespace: default # Change your namespace
spec:
  tags: ["STIG", "MYSQL"]
  message: "Alert! Non MySQL binaries were accessed inside pod"
  selector:
    matchLabels:
      container: mysql # <--- add your own match labels
  process:
    severity: 5
    matchPaths:
      - path: /bin/cd
    action: Block
