# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-stig-v-230558-ftp-binary
  namespace: default # Change your namespace
spec:
  tags: ["STIG", "RHEL8","REDHAT","FTP"]
  message: "Alert! FTP binary access detected and blocked. Violation of STIG v230558"
  selector:
    matchLabels:
      app: rhel8 # <--- add your own match labels
  process:
    severity: 5
    matchPaths:
      - path: /usr/sbin/vsftpd
    action: Block
