# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/
# https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-12-03/finding/V-230248

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-stig-rhel-v-230248
  namespace: default # Change your namespace
spec:
  tags: ["STIG", "RHEL", "V-230248", "File-Permissions", "Log-Files"]
  message: "Alert!  Permission to the log directories has been revoked."
  selector:
    matchLabels:
      app: redhat # Change your matchLabels
  file:
    severity: 4
    matchDirectories:
      - dir: /var/log/
        recursive: true
        fromSource:                         
        - path: /usr/bin/chmod
    action: Block


