# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-sc-28-1-information-at-rest
  namespace: default   #change with your namespace
spec:
  tags: ["NIST","SC-28-1-","SYSTEM-AND-COMMUNICATION","PCF"] 
  message: "Alert! Memory info accessed by unknown user"
  selector:
    matchLabels:
      container: test   #change with your match label
  file:
    severity: 7
    matchPaths:
    - path: /proc/meminfo
    - path: /proc/mounts
    action: Audit
