# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-cve-2021-41277-metabase-file-inclusion
  namespace: default # Change to your namespace
spec:
  tags: ["CVE", "Metabase", "File Inclusion", "CVE-2021-41277"]
  message: "Auditing Metabase access"
  selector:
    matchLabels:
      app: metabase  #Change to labels of frontend web application pod 
  file:
    severity: 5
    matchPatterns:
    - pattern: /**/*
    action: Block
  process:
    severity: 5
    matchDirectories:
    - dir: /app/
      recursive: true
    - dir: /opt/java/openjdk/bin/
      recursive: true
    - dir: /bin/
      recursive: true
    - dir: /usr/local/bin/
      recursive: true
    - dir: /usr/bin/
      recursive: true
    - dir: /usr/glibc-compat/bin/
      recursive: true
    action: Allow
  file:
    severity: 5
    matchDirectories:
    - dir: /app/
      recursive: true
    - dir: /etc/
      recursive: true
      fromSource: 
      - path: /usr/sbin/addgroup
    - dir: /etc/
      recursive: true
      fromSource: 
      - path: /usr/sbin/adduser
    action: Allow
