# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-cve-2022-0543-redis-rce
  namespace: default        #change default namespace to match your namespace
spec:
  tags: ["Redis-Server","Debian", "CVE", "CVE-2022-0543","RCE","Lua Sandbox Escape"]
  message: Alert! Possible CVE-2022-0543 (Redis Lua Sandbox Escape) denied.  
  selector:
    matchLabels:
      app: redis-cart
  file: 
    severity: 2
    matchPaths:
    - path: /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
    matchPatterns:
    - pattern: /**/liblua*
    action: Block
  process: 
    severity: 2
    matchPatterns:
    - pattern: /**/bin/**
    action: Block
