# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-grafana-cve-2021-43798
  namespace: default # Change your namespace
spec:
  tags: ["GRAFANA","CVE-2021-43798","TRAVERSAL"]
  message: Alert! directory traversal attack stopped.
  selector:
    matchLabels:
      app: grafana # Change your match labels
  file:
    severity: 5
    matchPaths:
    - path: /conf/defaults.ini
    - path: /conf/grafana.ini
    - path: /etc/grafana/grafana.ini
    - path: /etc/grafana/defaults.ini
    - path: /etc/passwd
    - path: /etc/shadow
    - path: /home/grafana/.bash_history
    - path: /home/grafana/.ssh/id_rsa
    - path: /root/.bash_history
    - path: /root/.ssh/id_rsa
    - path: /usr/local/etc/grafana/grafana.ini
    - path: /var/lib/grafana/grafana.db
    matchPatterns:
    - pattern: /**/public/plugins/alertlist/etc/passwd
    action: Block
  process:
    severity: 5
    matchPaths:
    - path: /proc/net/fib_trie
    - path: /proc/net/tcp
    - path: /proc/self/cmdline
    action: Block


