# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-cve-2019-6446-deny-pickle-rce-on-pod
  namespace: default # Change your namespace
spec:
  tags: ["PICKLE", "RCE", "EDB-ID-49585", "CVE-2019-6446"]
  message: "Execution of binary files blocked"
  selector:
    matchLabels:
      app: pickle-app #change app: pickle-app to match your label
  process:
    severity: 8
    matchDirectories:
    - dir: /usr/bin/
      recursive: true
    - dir: /bin/
      recursive: true
    - dir: /usr/local/bin/
      recursive: true
    action: Block
