# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-pci-dss-10.2.1-audit-user-details
  namespace: default    #change to your namespace
spec:
  message: "User related details are read/modified"
  tags: ["pci-dss", "10.2.1", "user", "system", "mysql"]
  selector:
    matchLabels:
      app: mysql    #change to your own label
  file:
    severity: 6
    matchPaths:
      - path: /etc/shadow
      - path: /etc/passwd
    action: Audit
  process:
    severity: 5
    matchPaths:
      - path: /usr/bin/mysql
    action: Audit
