# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-pci-dss-8-audit-utmp-file
  namespace: default # Change your namespace
spec:
  tags: ["PCI-DSS"] 
  message: "Alert! Access to log file utmp is detected"
  selector:
    matchLabels:
      pod: test  #change app: test to match your label
  file:
    severity: 5
    matchPaths:
    - path: /var/log/utmp
    action: Audit
