# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-deny-rce-on-flask-app-pod
  namespace: default # Change your namespace
spec:
  tags: ["FLASK", "RCE", "K8s", "Python"]
  message: "Execution of binary files blocked"
  selector:
    matchLabels:
      app: flask-app #change app: flask-app to match your label
  process:
    severity: 5
    matchDirectories:
    - dir: /usr/bin/
      recursive: true
    - dir: /bin/ 
      recursive: true
    - dir: /usr/local/bin/ 
      recursive: true
    action: Block
