# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-best-practice-cassandra-server-audit-jmx-password-file
  namespace: default # Change your namespace
spec:
  tags: ["CASSANDRA", "BEST PRACTICE"]
  message: "Cassandra server JMX password file accessed"
  selector:
    matchLabels:
      app: cass-server #change app: cass-server to match your label
  file:
    severity: 5
    matchPaths:
    - path: /etc/cassandra/jmxremote.password
      ownerOnly: true
    action: Audit
