# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-bower-json-logs
  namespace: default # use your namespace label here
spec:
  message: Access deined for  file bower.json
  tags : ["Bower","json","exposure"]
  selector:
    matchLabels:
       app: my-nginx  # use your own labels here
  file:
    matchPatterns: 
    - pattern: /**/bower.json
      readOnly: false
    severity: 4
    action: Block
