---
# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-deny-qdpm-info-leak-on-public-web
  namespace: default # Change to your namespace
spec:
  tags: ["qdPM", "info-leak", "exposures", "configs"]
  message: "Auditing qdPM access"
  selector:
    matchLabels:
      app: qdpm-server  #Change app: qdpm-server to labels of frontend web application pod 
  file:
    severity: 
    matchPatterns:
    - pattern: /**/databases.yml
    action: Block
