# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-robomongo-credential-disclosure
  namespace: default # Change to your namespace
spec:
  tags: ["mongodb", "robomongo", "robo3t", "disclosure", "config"]
  message: "Alert! Robomongo/Robo3t credentials accessed"
  selector:
    matchLabels:
      app: robomongo  #Change app=robomongo to your labels 
  file:
    severity: 5
    matchPatterns:
    - pattern: /**/robomongo.json
    action: Block
