# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-squid-reports
  namespace: default # use your own labels here
spec:
  message: Access deined for  file squid-reports
  tags : ["sarg","squid-reports","exposure"]
  selector:
    matchLabels:
       app: any  # use your own labels here
  file:
    matchPatterns: 
    - pattern: /**/squid-reports/**
    severity: 4
    action: Block
