# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-htpasswd-detection
  namespace: default # Change your name space
spec:
  tags: ["APACHE", "HTPASSWD", "EXPOSURE"]
  message: ".htpasswd file and/or htpasswd command is used and access has been denied"
  selector:
    matchLabels:
      app: apache-webserver # Change your matchLabels
  file:
    severity: 5
    matchPatterns:
    - pattern: /**/.htpasswd   # regex to get path of .htpasswd file
  action: Block
  process:
    severity: 5
    matchPatterns:
    - pattern: /**/htpasswd   # regex to get htpasswd command path. htpasswd is used to add new user to .htpasswd file
    action: Block
