# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-samba-config-file-disclosure
  namespace: default # Change to your namespace
spec:
  tags: ["config","exposure","smb","samba"]
  message: "samba config file blocked"
  selector:
    matchLabels:
      app: samba  #Change to labels of samba application pod 
  file:
    severity: 6
    matchPatterns:
    - pattern: /**/smb.conf
    action: Block
