# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-system-file-analysis
  namespace: default # Change your namespace
spec:
  tags: ["MITRE", "system", "T1003"]
  message: “Suspicious! Someone Tried to Access the System User files”
  selector:
    matchLabels:
      pod: ubuntu #change the labels
  process: 
    severity: 7         
    matchPaths: 
    - path: /etc/passwd
    - path: /etc/shadow
    action: Audit
