# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 


apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-check-log-clearing
  namespace: default # Change your namespace
spec:
  tags: ["MITRE", "Defense Evasion"]
  message: "Defense evasion clear linux system logs"
  selector:
    matchLabels:
      container: ubuntu # Change your own match labels
  file:
    severity: 5
    matchDirectories:
    - dir: /var/log/
      recursive: true
      readOnly: true
    - dir: /dev/log/
      recursive: true
      readOnly: true
    action: Audit
 
