# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-persistence-bash-profile
  namespace: default # Change your namespace
spec:
  tags: ["MITRE", "Persistence", "K8s"]
  message: "Warning! Someone accessed profile details"
  selector:
    matchLabels:
      app: testpod #change with your own label
  file:
    matchPaths:
      - path: /root/.bash_profile
        readOnly: true
      - path: /root/.bashrc
        readOnly: true
      - path: /etc/profile
        readOnly: true
    action: Audit
    severity: 4
