# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-sub-processes-of-netcat
  namespace: default # Change your namespace
spec:
  tags: ["MITRE"]
  message: "binary forked through netcat"
  selector:
    matchLabels:
      app: testpod #change with your own label
  process:
    matchPaths:
      - path: /usr/bin/**
        fromSource:
        - path: /usr/bin/netcat
      - path: /usr/bin/**
        fromSource:
        - path: /usr/bin/nc
    action: Audit
    severity: 4
