# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mitre-tactic-impair-defence
  namespace: default  #change with your namespace
spec:
  tags: ["MITRE", "T1562"]
  message: "Selinux Files Accessed by Unknown Process"
  selector:
    matchLabels:
      app: testpod #change with your match label
  file:
    severity: 6
    matchPaths:
    - path: /etc/selinux/semanage.conf
    - path: /etc/sysconfig/selinux
    - path: /etc/apparmor.d
    action: Audit
