# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:    
  name: ksp-block-mysql-dump-in-pods
  namespace: default        # Change your namespace
spec:
  tags: ["mysql", "system", "K8s", "MITRE"]
  message: "Warning! MySQLdump is blocked"
  selector:      
    matchLabels:        
      app: testpod    #change with your own label    
  process:      
    matchPaths:      
    - path: /usr/bin/mysqldump    
    action: Block    
    severity: 6
